/**
 * @file config.h
 * @brief SSDK configuration header file.
 *
 * @copyright Copyright (c) 2022 Semidrive Semiconductor.
 *            All rights reserved.
 */

#define CONFIG_ARMV8R 1
#define CONFIG_ARCH_WITH_CACHE 1
#define CONFIG_ARCH_CACHE_LINE 64
#define CONFIG_ARCH_EARLY_ENABLE_ICACHE 1
#define CONFIG_ARCH_EARLY_ENABLE_DCACHE 1
#define CONFIG_ARCH_WITH_FPU 1
#define CONFIG_ARCH_WITH_MPU 1
#define CONFIG_ARCH_CHIP_E3 1
#define CONFIG_ARM_WITH_TCM 1
#define CONFIG_ARM_TCMC_WITHOUT_CLEAR 1
#define CONFIG_ARM_TCM_BASE 0x00
#define CONFIG_ARMV8R_USE_TCMA 1
#define CONFIG_ARMV8R_USE_TCMB 1
#define CONFIG_ARMV8R_USE_TCMC 1
#define CONFIG_ARM_WITH_CP15 1
#define CONFIG_ARM_WITH_PMU 1
#define CONFIG_IRQ 1
#define CONFIG_DEBUG 1
#define CONFIG_DEBUG_LEVEL SSDK_DEBUG
#define CONFIG_PRINTF_LIB 1
#define CONFIG_EARLYCOPY 1
#define CONFIG_HOST_MBOX 1
#define CONFIG_INIT_MRAM 1
#define SEC_VERSION_FUSE_BURN 1
#define SUPPORT_HASH_CALC_BY_SOFTWARE 1
#define CONFIG_LOAD_VERIFY_IIB_PARALLEL 0
#define CONFIG_SECURE_BOOT_VERIFY_WITH_SE_ROM 1
